CREATE DATABASE IF NOT EXISTS PROJECT;

USE PROJECT;

CREATE TABLE IF NOT EXISTS `EMPLOYEE` (
	`ID` BIGINT(10) NOT NULL AUTO_INCREMENT,
	`FIRSTNAME` VARCHAR(50) NULL DEFAULT NULL,
	`LASTNAME` VARCHAR(50) NULL DEFAULT NULL,
	`BIRTH_DATE` DATE NOT NULL,
	`CELL_PHONE` VARCHAR(15) NOT NULL,
	PRIMARY KEY (`ID`)
)
COLLATE=`LATIN1_SWEDISH_CI`
ENGINE=INNODB
ROW_FORMAT=DEFAULT
AUTO_INCREMENT=606;

DROP TABLE IF EXISTS `PROJECT`.`CONTROL_PROCESS`;
CREATE TABLE IF NOT EXISTS `CONTROL_PROCESS` (
	`ID` BIGINT(10) NOT NULL AUTO_INCREMENT,
	`CONTROL_PROCESS_ID` VARCHAR(100) NOT NULL,
	`USERNAME` VARCHAR(50) NULL DEFAULT NULL,
	`START_TIME` DATE NOT NULL,
	`END_TIME` DATE NOT NULL,
	`PROCESS_TYPE` VARCHAR(50) NOT NULL,
	`STATUS` VARCHAR(50) NOT NULL,
	PRIMARY KEY (`ID`) USING BTREE
)ENGINE=InnoDB AUTO_INCREMENT=34 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `PROJECT`.`CONTROL_PROCESS_DETAIL`;
CREATE TABLE IF NOT EXISTS `CONTROL_PROCESS_DETAIL` (
	`CONTROL_PROCESS_DETAIL_ID` BIGINT(10) NOT NULL AUTO_INCREMENT,
	`CONTROL_PROCESS_ID` BIGINT(10) NOT NULL,
	
	`BASECONTROLFILENAMEWITHLOC` VARCHAR(1000) NULL DEFAULT NULL,
	`BASEDATFILENAMEWITHLOC` VARCHAR(1000) NULL DEFAULT NULL,
	`BASEMETAFILENAMEWITHLOC` VARCHAR(1000) NULL DEFAULT NULL,
	
	`DESTCONTROLFILENAMEWITHLOC` VARCHAR(1000) NULL DEFAULT NULL,
	`DESTDATFILENAMEWITHLOC` VARCHAR(1000) NULL DEFAULT NULL,
	`DESTMETAFILENAMEWITHLOC` VARCHAR(1000) NULL DEFAULT NULL,
	
	`HDFSCTLFILELOC` VARCHAR(100) NULL DEFAULT NULL,
	`HDFSMETAFILELOC` VARCHAR(50) NULL DEFAULT NULL,
	`HDFSDATFILELOC` VARCHAR(50) NULL DEFAULT NULL,
	
	`SCHEMAVALIDATION` VARCHAR(50) NULL DEFAULT NULL,
	`ROWCOUNTVALIDATION` VARCHAR(50) NULL DEFAULT NULL,
	`CRCVALIDATION` VARCHAR(50) NULL DEFAULT NULL,
	
	`CTLROWCOUNTEXIST` BIT NOT NULL DEFAULT 0,
	`CTLROWCOUNT` BIGINT(10) NOT NULL,
	`COMPUTEDROWCOUNT` BIGINT(10) NOT NULL,
	
	`DETAILLOGFILELOC` VARCHAR(500) NOT NULL,
	
	`INSERTEDDATE` DATE NOT NULL,
	`UPDATEDDATE` DATE NOT NULL,
	`STATUS` VARCHAR(50) NOT NULL,
	
	PRIMARY KEY (`CONTROL_PROCESS_DETAIL_ID`) USING BTREE,
	KEY `FK_CONTROL_PROCESS_ID` (`CONTROL_PROCESS_ID`),
	CONSTRAINT `FK_CONTROL_PROCESS_ID` FOREIGN KEY (`CONTROL_PROCESS_ID`) REFERENCES CONTROL_PROCESS(`ID`)
	ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB AUTO_INCREMENT=36 DEFAULT CHARSET=utf8;

	
